import { DataTypes, Model } from 'sequelize';
import { sequelize } from '../config/database';

/**
 * Represents a User entity in the system.
 * Handles authentication, roles, and application access status.
 * 
 * @class users
 * @extends {Model}
 */
export class users extends Model {
    /** 
     * Unique auto-incrementing identifier.
     * @type {number} 
     */
    declare id: number;

    /** 
     * Unique email address of the user.
     * @type {string} 
     */
    declare email: string;

    /** 
     * Encrypted password for authentication.
     * @type {string} 
     */
    declare password: string;

    /** 
     * Role assigned within the platform for access control.
     * @type {string} 
     * @default 'REQUEST_MANAGER'
     */
    declare role: string;

    /** 
     * Activity status of the user in the system.
     * @type {boolean} 
     * @default true
     */
    declare active: boolean;

    /** 
     * Record creation timestamp (Generated by Sequelize).
     * @type {Date} 
     */
    declare createdAt: Date;

    /** 
     * Last update timestamp (Generated by Sequelize).
     * @type {Date} 
     */
    declare updatedAt: Date;

    /** 
     * Logical deletion date (Enabled by paranoid mode).
     * @type {Date | null} 
     */
    declare deletedAt: Date | null;
}

// Model initialization with Sequelize
users.init(
    {
        /**
         * Auto-incrementing primary key of the user.
         */
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            allowNull: false
        },
        /**
         * Institutional or personal email address. Must be unique.
         */
        email: {
            type: DataTypes.STRING,
            allowNull: false,
            unique: true
        },
        /**
         * Security password hash.
         */
        password: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        /**
         * User permissions. Assigned as 'REQUEST_MANAGER' by default.
         */
        role: {
            type: DataTypes.STRING,
            defaultValue: 'REQUEST_MANAGER',
            allowNull: false
        },
        /**
         * Controls whether the user can sign in.
         */
        active: {
            type: DataTypes.BOOLEAN,
            defaultValue: true,
            allowNull: false
        }
    },
    {
        sequelize: sequelize,
        tableName: "users",
        timestamps: true, // Automatically enables createdAt and updatedAt
        paranoid: true    // Enables deletedAt for soft-delete
    }
);
