import { DataTypes, Model } from 'sequelize';
import { sequelize } from '../config/database';

/**
 * Represents a Warehouse entity in the system.
 * Manages storage facilities, locations, and operational availability.
 * 
 * @class warehouse
 * @extends {Model}
 */
export class warehouse extends Model {
    /** 
     * Unique auto-incrementing identifier for the warehouse.
     * @type {number} 
     */
    declare id: number;

    /** 
     * Official name of the storage facility.
     * @type {string} 
     */
    declare name: string;

    /** 
     * Physical address or geographical location of the warehouse.
     * @type {string} 
     */
    declare location: string;

    /** 
     * Operational status of the warehouse in the platform.
     * @type {boolean} 
     * @default true
     */
    declare active: boolean;

    /** 
     * Record creation timestamp (Generated by Sequelize).
     * @type {Date} 
     */
    declare createdAt: Date;

    /** 
     * Last update timestamp (Generated by Sequelize).
     * @type {Date} 
     */
    declare updatedAt: Date;

    /** 
     * Logical deletion date (Enabled by paranoid mode).
     * @type {Date | null} 
     */
    declare deletedAt: Date | null;
}

// Model initialization with Sequelize
warehouse.init(
    {
        /**
         * Auto-incrementing primary key of the warehouse.
         */
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            allowNull: false
        },
        /**
         * Name of the storage warehouse.
         */
        name: {
            type: DataTypes.STRING,
            allowNull: false
        },
        /**
         * Physical location of the warehouse.
         */
        location: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        /**
         * Controls whether the warehouse is active and available in the system.
         */
        active: {
            type: DataTypes.BOOLEAN,
            defaultValue: true,
            allowNull: false
        }
    },
    {
        sequelize: sequelize,
        tableName: "warehouses",
        timestamps: true, // Automatically enables createdAt and updatedAt
        paranoid: true    // Enables deletedAt for soft-delete
    }
);
